services:
  guacamole:
    depends_on:
      guacd:
        condition: service_healthy
      guacdb:
        condition: service_healthy
    image: guacamole/guacamole
    container_name: guacamole
    restart: always
    env_file: .env
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: guacdb
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: guacamole_user
    networks:
      guacnet:
    links:
      - guacd
      - guacdb

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: always
    volumes:
      - drive:/drive
      - record:/record
    networks:
      guacnet:

  guacdb:
    image: postgres
    container_name: guacdb
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./Docker/guacdb/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - dbdata:/var/lib/postgresql/data
    networks:
      guacnet:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  guacproxy:
    build: ./Docker/guacproxy
    image: guacproxy
    container_name: guacproxy
    restart: always
    ports:
      - 60443:443
    links:
      - guacamole
    networks:
      guacnet:

volumes:
  drive:
  record:
  dbdata:

networks:
  guacnet:
    driver: bridge
